articles/urls.py


from django.contrib import admin
from django.urls import path, include
from . import views


app_name= "articles"
urlpatterns = [
    path('',views.article, name ="articles"),
    path('création_article/', views.créer, name= "créer"),
    path('<slug:slug>/', views.contenus, name = "contenus_article")
   
]

articles/models.py
from django.db import models

class Articles(models.Model):
    titre= models.CharField(max_length=150)
    contenu= models.TextField()
    date_publication= models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now = True)
    slug = models.SlugField(max_length=100)
    image = models.ImageField(default="default.jpg")
    


    def __str__(self):
        return self.titre

articles/forms.py

from django.forms import ModelForm
from .models import Articles

class FormArticles(ModelForm):
    class Meta:
        model= Articles
        fields = ['titre','contenu','image','slug']

articles/views.py

from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Articles
from django.http import HttpResponseRedirect
from django.urls import reverse #retourner les fonctions par les noms des url

from .forms import FormArticles



def article(request):
    articles=Articles.objects.all().order_by('-date_publication')
    return render(request,'articles/list.html',context={'articles':articles})


def contenus(request, slug):

        article = get_object_or_404(Articles, slug=slug)
        return render(request,'articles/detail.html', context={'article':article})
    # try:
    #     article = Articles.objects.get(slug=slug)
    #     return render(request,'articles/detail.html', context={'article':article})
    # except Articles.DoesNotExist:
    #     raise Http404("l'article n'existe pas..")

def créer(request):
    form = FormArticles() 
    # ceci est l'objet de la class FormArticles
    # nous allons récupérer nos données ds la bd
    if request.method == 'POST':
        form = FormArticles(request.POST)
        if form.is_valid():
            titre = form.cleaned_data['titre']
            contenu = form.cleaned_data['contenu']
            image = form.cleaned_data['image']
            slug = form.cleaned_data['slug']
            form.save() #pour sauvegarder les données ds la bd
            # return HttpResponseRedirect('/articles/')
        return HttpResponseRedirect(reverse('articles:articles'))
    return render(request,'articles/créer.html', context={'form':form})

articles/templates/articles/créer.html

{%extends 'baseTemplate.html'%}
{%block contenu%}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <h1>nouveaux articles</h1>
            <hr>
            <form action="{% url 'articles:créer'%}" method="POST" >
                {% csrf_token %}
                {{form}}
            <button type="submit" class="btn btn-success">créer</button>
            </form>
        </div>
    </div>
</div>
    
{%endblock%}

articles/templates/articles/detail.html

{%extends 'baseTemplate.html'%}
    {%block contenu%}
        <div class="container mt-4"><h3>{{article.titre}}</h3></div>
        <hr>
        <div class="row">
            <div class="col-lg-6">
                <div class="container">
                    <p> 
                        {{article.contenu}}
                    </p>
                    <span>{{article.date_publication}}</span>
                    <button type="button" class="btn btn-secondary">voir plus..</button> 
                </div>
            </div>
            <div class="col-lg-6">
                <span><img class="w-100"width="509" height="340" src="{{article.image.url}}" alt="{{article.titre}}"></span>
            </div>
        </div>
        <div class="mb-3"></div>
        
        <!-- <img src="{{article.image.url}}" alt="{{article.titre}}">
        <p> 
            {{article.contenu}}
        </p>
        <span>{{article.date_publication}}</span>
        <button type="button" class="btn btn-secondary">voir plus..</button> -->
    {%endblock%}

articles/templates/articles/list.html

{%extends 'baseTemplate.html'%}
{%block titre%}page d'article{%endblock%}
    {%block contenu%}
        <!-- <h1 class="titre">les articles</h1>
        <a href="{% url 'articles:créer'%}" class="btn btn-primary">
            créer
        </a> -->
        <div class="container mt-4">
            <div class="row">
                <div class="col-lg-11"><p class="h1">liste des articles</p></div>
                
                <div class="col-lg-1"><a href="{% url 'articles:créer'%}" class="btn btn-primary">
                    créer </a></div>
            </div>
        </div><hr>
        <div class="container">
            {%for article in articles%}
                <h2> <a href="{%url 'articles:contenus_article' slug=article.slug%}">{{article.titre}}</a></h2>
                <p>{{article.contenu}}</p>
                <span>{{article.date_publication}}</span>
            {% endfor%}
        </div>
        <div class="mb-5"></div>
       
    {%endblock%}